language: php

dist: xenial

addons:
  apt_packages:
    - rabbitmq-server

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.2
    # Build ensuring minimum dependencies are valid
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - sudo apt update
  - sudo apt install -y librabbitmq-dev
  - yes '' | pecl install -f amqp

script:
  - vendor/bin/phpunit
