language: php

matrix:
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
          env: deps=high
        - php: 7.2
          env: deps=low
        - php: 7.2
          env: deps=high
    fast_finish: true

group: edge
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

install:
  - composer install -n
